FROM node:20-alpine3.20 AS installer


WORKDIR /app

COPY package*.json ./

COPY tsconfig.json .

RUN yarn install --frozen-lockfile

FROM installer as builder

COPY . .

RUN yarn build 

FROM nginx:stable-alpine AS production

COPY --from=builder /app/dist /usr/share/nginx/html

# copy file cấu hình 
COPY nginx/nginx.conf  /etc/nginx/nginx.conf

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]